#!/bin/sh

set -e

bundle install

if [ -z "${CI:-}" ]; then
  # CI does not accept all commands and has already created user and the database
  DB_USER="postgres"
  DB_NAME="browse_test"
  psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || createuser --superuser $DB_USER
  psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE $DB_NAME"
fi

script/update
